language: python

cache:
  - pip
  - ccache

matrix:
    include:
        - os: linux
          python: "2.7"
        - os: linux
          python: "3.6"

install:
    - pip install coverage coveralls
    - pip install Cython
    - python setup.py sdist
    - pip install dist/*.tar.gz

script:
    - pip install flake8 && flake8 --config=.flake8.cython
    - coverage run --source=pysfmt setup.py test

after_success:
    - coveralls

notifications:
    email: false
